# Use postgres/example user/password credentials
version: '3.1'

services:

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
    - 5672:5672
    - 15672:15672

  postgresdb:
    image: postgres
    restart: always
    ports:
    - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: user_auth
    volumes:
    - ./postgres:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgresdb

  gateway:
    build: back_end/gateway
    ports:
      - 4000:4000
    depends_on:
      - postgresdb
    links:
      - postgresdb
    environment:
      DATABASE_HOST: postgresdb
    command: ["./wait-for-it.sh", "postgresdb:5432/auth_db", "--", "python", "./app.py"]

  front-end:
    build: front_end
    ports:
      - 3000:3000
    stdin_open: true



