apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: fsm
  name: fsm
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: fsm
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.network/docker_network: "true"
        io.kompose.service: fsm
    spec:
      containers:
      - args:
        - ./wait-for-it.sh
        - rabbitmq:5672
        - --
        - python
        - ./views.py
        env:
        - name: IN_CONTAINER_FLAG
          value: "1"
        image: diarmuidk/wacc:fsm
        imagePullPolicy: Always
        name: fsm
        volumeMounts:
          - mountPath: "~/logs"
            name: mypd
        ports:
        - containerPort: 4500
        resources: {}
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
        - name: mypd
          persistentVolumeClaim:
            claimName: pvc
status: {}
