version: "2"
services:
  app:
    build: ./app
    links:
      - db
    ports:
      - "5000:5000"
  db:
    image: mysql:5.7
#    environment:
#        MYSQL_DATABASE: "fileServiceMgr"
#        MYSQL_ROOT_PASSWORD: "root"
#        MYSQL_USER: "group12"
#        MYSQL_PASSWORD: "group12"
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: fileServiceMgr
#      MYSQL_USER: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
